version: '3.8'

services:

  app2:
    container_name: app2
    build: app2/.
    restart: on-failure
    env_file: app2/.env
    environment:
      APP_NAME: app2
    tty: true
    stdin_open: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password